[pygbag]
# Pygbag設定ファイル

# ウィンドウ設定
width = 1280
height = 720
title = "Mystery Pet Rescue"

# ビルド設定
archive = true
cdn = "https://cdn.jsdelivr.net/pyodide/"

# パフォーマンス設定
fps = 30  # Web版は30fpsに下げる
optimize = true

# 非同期設定
async_main = true

# CORS設定
# Web環境でのリソース読み込み問題を解決
template = "custom"

# 除外ファイル（ビルドに含めない）
exclude = [
    "*.pyc",
    "__pycache__/",
    ".git/",
    ".pytest_cache/",
    "tests/",
    "examples/",
    "docs/",
    "logs/",
    ".env",
    "requirements-dev.txt",
    "build_web.py",
    "serve_web.py"
]

# 含めるアセット
include = [
    "assets/",
    "data/",
    "config/",
    "locales/"
]

# フォント設定
[fonts]
# 日本語フォント設定
preload = ["assets/fonts/NotoSansJP-VariableFont_wght.ttf"]
default_font = "assets/fonts/NotoSansJP-VariableFont_wght.ttf"
