[pygbag]
# Pygbag設定ファイル

# ゲーム情報
name = "Mystery Pet Rescue"
author = "Game Developer"
version = "1.0.0"
description = "迷子のペットを探して救出するアドベンチャーゲーム"

# ウィンドウ設定
width = 1280
height = 720
title = "ミステリー・ペット・レスキュー"

# アセット設定
icon = "assets/icons/game_icon.png"
archive = true
cdn = "https://cdn.jsdelivr.net/pyodide/"

# パフォーマンス設定
fps = 60
vsync = true

# Web固有設定
template = "custom"
loading_text = "ゲーム読み込み中..."
fullscreen = false

# 除外ファイル
exclude = [
    "*.pyc",
    "__pycache__",
    ".git",
    ".pytest_cache",
    "tests/",
    "examples/",
    "docs/",
    "logs/",
    ".env",
    "requirements-dev.txt"
]

# 含めるアセット
include = [
    "assets/images/",
    "assets/sounds/",
    "assets/music/",
    "assets/icons/",
    "data/",
    "config/",
    "locales/"
]
