name: Build and Deploy Web Version

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame
        pip install pygbag
        pip install -r requirements.txt
    
    - name: Build web version with Pygbag
      run: |
        python -m pygbag --build main.py
        echo "Build completed successfully"
        ls -la build/web/
    
    - name: Prepare deployment files
      run: |
        # Copy built game files
        cp -r build/web/* docs/github-pages/
        
        # Rename the built index.html to game.html to preserve our custom index.html
        mv docs/github-pages/index.html docs/github-pages/game.html
        
        # Restore our custom index.html from git
        git checkout HEAD -- docs/github-pages/index.html
        
        echo "Deployment files prepared:"
        ls -la docs/github-pages/
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/github-pages
        publish_branch: gh-pages
        force_orphan: true
        commit_message: '🚀 Auto-deploy web version via GitHub Actions'